kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kema8s
nodes:
  # Control planes
  - role: control-plane
    extraMounts:
      # Permit disks (and other stuff) discovery
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: control-plane
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: control-plane
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev

  # AZ 1
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      # Permit bind-mounting application code inside (nodes then) app containers
      # NOTE `../../../` is relative to cwd, not config file directory! We intend to mount repository parent directory
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org

  # AZ 2
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org

  # AZ 3
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org
  - role: worker
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
      - hostPath: ../../../
        containerPath: /git-vcs-org

networking:
  ipFamily: ipv6
  # Let cilium be exclusive CNI
  disableDefaultCNI: true
  # Let cilium replace kube-proxy
  kubeProxyMode: none
  # Set IPv6 subnets (randomly generated)
  podSubnet: "fd79:5929:1f89:41d::/56"
  serviceSubnet: "fd57:4a0f:7b76:4008::/112"
