name: Global - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  secrets-scan:
    name: Secrets scan
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      # Use runner user, see https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Secrets scan
        id: secrets-scan
        run: kema-runner secrets

  deps-scan:
    name: Dependencies scan
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      # Use runner user, see https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Dependencies scan
        id: deps-scan
        run: kema-runner deps

  sast:
    name: Static Application Security Testing
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      # Use runner user, see https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: SAST
        id: sast
        run: kema-runner sast
