name: Go - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked
    paths:
      - '**go.mod'
      - '**go.sum'
      - '**.go'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  go-unit-test:
    name: Go unit test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      env:
        # Make race detection possible
        CGO_ENABLED: 1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Go unit test
        id: go-unit-test
        run: kema-runner go-test

  go-test-coverage:
    name: Go test coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Go test coverage
        id: go-test-coverage
        run: kema-runner go-cover

  go-check-mod-tidy:
    name: Go go.mod tidyness
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Go go.mod tidyness
        id: go-check-mod-tidy
        run: kema-runner go-mod-tidy

  go-check-mod-name:
    name: Go go.mod name
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Go go.mod name
        id: go-check-mod-name
        run: kema-runner go-mod-name

  go-lint:
    name: Go lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set git safe directory
        run: git config --global --add safe.directory "/__w/${{ github.repository }}"
      - name: Go lint
        id: go-lint
        run: kema-runner go-lint
