name: Markdown - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked
    paths:
      - '**.md'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd-runner:latest
      # Use runner user, see https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Markdown lint
        id: markdown-lint
        run: kema-runner markdown
