name: app

networks:
  app-main:
    driver: bridge

secrets:
  netrc:
    name: netrc
    # TIP You can use `export COMPOSE_NETRC="$(echo -e "machine $(git remote get-url origin | grep -oP '.+://\K[^/]+(?=/)')\nlogin git\npassword $(gh auth token)\n")"`
    environment: COMPOSE_NETRC

services:
  app:
    # Enable colorized output for air
    tty: true
    build:
      context: ../../
      dockerfile: build/Dockerfile
      target: dev
    networks:
      - app-main
    secrets:
      - netrc
    environment:
      GO_MAIN_FILE_DIR: ./cmd/main
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /src
    # Close immediately and let compose restart the container without waiting for graceful shutdown
    stop_grace_period: 0s
